Attachment processing: find/execute '.stodo-shell'
Attachment processing: If the "current" attachment is a directory and
if there is an executable file in that directory called .stodo-shell,
execute it.

Also:

README.md: Updated to match recent changes, such as the new attachments-
processing feature.

New 'version' command and supporting constant/method in Configuration.

STodoAdministrator: bug fix in 'perform_data_backup': This line:
    config = Configuration.instance
was in the wrong place.

Some small improvements to tests re reporting results.

diff --git a/test/add-change-delete-etc-101 b/test/add-change-delete-etc-101
--- a/test/add-change-delete-etc-101
+++ b/test/add-change-delete-etc-101
@@ -1,6 +1,7 @@
 #!/bin/bash
 # (define env. var. STODO_KEEP_ARTIFACTS to force any new items to NOT
 # be deleted.)
+# vim: expandtab ts=2 sw=2
 
 parse_args() {
   for arg; do
@@ -13,6 +14,7 @@ parse_args() {
 }
 
 create_test() {
+  local result=0
   create $testhndl
   if report $testhndl|awk 'BEGIN { hitcount = 0; EXPCOUNT = 5 }
     /handle: *'$testhndl'/ {  ++hitcount }
@@ -31,12 +33,14 @@ create_test() {
   then
     echo "creation test SUCCEEDED"
   else
-    echo "creation test failed"
+    echo "creation test FAILED"
     exit 99
   fi
+  return $result
 }
 
 modify_test() {
+  local result=0
   modify $testhndl
   if report $testhndl|awk 'BEGIN { hitcount = 0; EXPCOUNT = 6 }
     /handle: *'$testhndl'/ {  ++hitcount }
@@ -56,23 +60,26 @@ modify_test() {
   then
     echo "modification test SUCCEEDED"
   else
-    echo "modification test failed"
-    exit 98
+    echo "modification test FAILED"
+    result=98
   fi
+  return $result
 }
 
 delete_test() {
+  local result=0
   if ! [ "$STODO_KEEP_ARTIFACTS" ]; then
     delete $testhndl
     if report $testhndl|grep -q "$testhndl"; then
-      echo "deletion test failed in deletion of $testhndl"
-      exit 97
+      echo "deletion test FAILED in deletion of $testhndl"
+      result=97
     else
       echo "deletion test SUCCEEDED"
     fi
   else
       echo "deletion test bypassed (keeping new item with handle: $testhndl"
   fi
+  return $result
 }
 
 # Set "vars" for origination/creation.
@@ -117,9 +124,18 @@ newttl="This is title number $$.  It is long."
 newttlregex="This.is.title.number.*It.is.long"
 newprio=3
 
+testcount=0
+successcount=0
 parse_args $@
 set_ovars
-create_test
+if create_test; then ((++successcount)); fi
+((++testcount))
 set_nvars
-modify_test
-delete_test
+if modify_test; then ((++successcount)); fi
+((++testcount))
+if delete_test; then ((++successcount)); fi
+((++testcount))
+[ $successcount = $testcount ]
+allgood=$?
+testreport $testcount $successcount
+exit $allgood
diff --git a/test/add-change-delete-etc-102 b/test/add-change-delete-etc-102
--- a/test/add-change-delete-etc-102
+++ b/test/add-change-delete-etc-102
@@ -13,6 +13,7 @@ parse_args() {
 }
 
 create_test() {
+  local result=0
   create $testhndl
   if report $testhndl|awk 'BEGIN { hitcount = 0; EXPCOUNT = 5 }
     /handle: *'$testhndl'/ {  ++hitcount }
@@ -31,12 +32,14 @@ create_test() {
   then
     echo "creation test SUCCEEDED"
   else
-    echo "creation test failed"
+    echo "creation test FAILED"
     exit 99
   fi
+  return $result
 }
 
 state_test() {
+  local result=0
   change_state $newstatecmd $testhndl
   if report $testhndl|awk 'BEGIN { state_is_correct = 0 }
     /status: *'$newstate'/ { state_is_correct = 1; state=$2; exit }
@@ -52,23 +55,26 @@ state_test() {
   then
     echo "state-change test SUCCEEDED"
   else
-    echo "state-change test failed"
-    exit 96
+    echo "state-change test FAILED"
+    result=96
   fi
+  return $result
 }
 
 delete_test() {
+  local result=0
   if ! [ "$STODO_KEEP_ARTIFACTS" ]; then
     delete $testhndl
     if report $testhndl|grep -q "$testhndl"; then
-      echo "deletion test failed in deletion of $testhndl"
-      exit 97
+      echo "deletion test FAILED in deletion of $testhndl"
+      result=97
     else
       echo "deletion test SUCCEEDED"
     fi
   else
       echo "deletion test bypassed (keeping new item with handle: $testhndl"
   fi
+  return $result
 }
 
 # Set "vars" for origination/creation.
@@ -112,9 +118,18 @@ desc='original, bland description'
 newstate=suspended
 newstatecmd=suspend
 
+testcount=0
+successcount=0
 parse_args $@
 set_ovars
-create_test
+if create_test; then ((++successcount)); fi
+((++testcount))
 set_nvars
-state_test
-delete_test
+if state_test; then ((++successcount)); fi
+((++testcount))
+if delete_test; then ((++successcount)); fi
+((++testcount))
+[ $successcount = $testcount ]
+allgood=$?
+testreport $testcount $successcount
+exit $allgood
diff --git a/test/attachments-101 b/test/attachments-101
--- a/test/attachments-101
+++ b/test/attachments-101
@@ -14,9 +14,9 @@ parse_args() {
 
 # Create an item that with attachments.
 create_item_with_attachments() {
+  local result=0
   create
   hndl=$ST_HANDLE
-echo "attchsexpr: '$attchsexpr'" >&2
   if report $hndl|awk 'BEGIN { hitcount = 0; EXPCOUNT = 6 }
     /handle: *'$hndl'/ {  ++hitcount }
     /title: *'"$mainttl"'/ {  ++hitcount }
@@ -35,47 +35,26 @@ echo "attchsexpr: '$attchsexpr'" >&2
   then
     echo "creation of $hndl SUCCEEDED"
   else
-    echo "creation of $hndl failed"
-    exit 99
+    echo "creation of $hndl FAILED"
+    result=99
   fi
-}
-
-modify_test() {
-  modify $testhndl
-  if report $testhndl|awk 'BEGIN { hitcount = 0; EXPCOUNT = 6 }
-    /handle: *'$testhndl'/ {  ++hitcount }
-    /title: *'"$newttlregex"'/ {  ++hitcount }
-    /email: *'$email'/ {  if (! emailset) { ++hitcount}; ++emailset }
-    /description: *'"$desc"'/ {  ++hitcount }
-    /type: *'$testtype'/ {  ++hitcount }
-    END {
-      if (hitcount != EXPCOUNT) {
-        print "(expected " EXPCOUNT " matches, got: " hitcount ")"
-        exit 1
-      } else {
-        exit 0
-      }
-    }'
-  then
-    echo "modification test SUCCEEDED"
-  else
-    echo "modification test failed"
-    exit 98
-  fi
+  return $result
 }
 
 delete_test() {
+  local result=0
   if ! [ "$STODO_KEEP_ARTIFACTS" ]; then
     delete $testhndl
     if report $testhndl|grep -q "$testhndl"; then
-      echo "deletion test failed in deletion of $testhndl"
-      exit 97
+      echo "deletion test FAILED in deletion of $testhndl"
+      result=97
     else
       echo "deletion test SUCCEEDED"
     fi
   else
       echo "deletion test bypassed (keeping new item with handle: $testhndl"
   fi
+  return $result
 }
 
 # Set "vars" for origination/creation.
@@ -118,7 +97,15 @@ attchs="$att1,$att2, $att3"
 attchsexpr=".*$att1.*$att2.*$att3"
 maindesc='task with attachments'
 
+testcount=0
+successcount=0
 parse_args $@
 set_main_vars
-create_item_with_attachments
-delete_test
+if create_item_with_attachments; then ((++successcount)); fi
+((++testcount))
+if delete_test; then ((++successcount)); fi
+((++testcount))
+[ $successcount = $testcount ]
+status=$?
+testreport $testcount $successcount
+exit $status
diff --git a/test/references-101 b/test/references-101
--- a/test/references-101
+++ b/test/references-101
@@ -1,6 +1,7 @@
 #!/bin/bash
 # (define env. var. STODO_KEEP_ARTIFACTS to force any new items to NOT
 # be deleted.)
+# vim: expandtab ts=2 sw=2
 
 parse_args() {
   for arg; do
@@ -29,14 +30,14 @@ create_ref() {
   then
     echo "creation of ref $hndl SUCCEEDED"
   else
-    echo "creation of ref $hndl failed"
+    echo "creation of ref $hndl FAILED"
     return 98
   fi
 }
 
 # Create an item that refers to the "references".
 # If an argument is supplied that evaluates to 'true', lie about failure
-# status - i.e., report: 'creation of $hndl "succeeded"' and return with
+# status - i.e., report: 'creation of $hndl "SUCCEEDED"' and return with
 # status value of $lie_retval.
 create_item_with_refs() {
   local lie=false
@@ -45,7 +46,6 @@ create_item_with_refs() {
   fi
   create
   hndl=$ST_HANDLE
-echo "refsexpr: '$refsexpr'" >&2
   if report $hndl|awk 'BEGIN { hitcount = 0; EXPCOUNT = 6 }
     /handle: *'$hndl'/ {  ++hitcount }
     /title: *'"$mainttl"'/ {  ++hitcount }
@@ -69,10 +69,10 @@ echo "refsexpr: '$refsexpr'" >&2
     echo "creation of $hndl SUCCEEDED$tail"
   else
     if eval $lie; then
-      echo "creation of $hndl \"succeeded\""
+      echo "creation of $hndl \"SUCCEEDED\""
       return $lie_retval
     else
-      echo "creation of $hndl failed"
+      echo "creation of $hndl FAILED"
       return 99
     fi
   fi
@@ -90,7 +90,7 @@ delete_test() {
   if ! [ "$STODO_KEEP_ARTIFACTS" ]; then
     delete $hndl$2
     if report $hndl|grep -q "$hndl"; then
-      echo "deletion of $hndl failed"
+      echo "deletion of $hndl FAILED"
       return 97
     else
       echo "deletion of $hndl SUCCEEDED"
@@ -171,6 +171,8 @@ badrefsexpr="$ref1[, ]*non-existence$$[, ]*$ref3"
 maindesc='task with references'
 lie_retval=42
 
+testcount=0
+successcount=0
 failures=0
 parse_args $@
 for handle in $ref1 $ref2 $ref3; do
@@ -178,37 +180,52 @@ for handle in $ref1 $ref2 $ref3; do
   create_ref
   stat=$?
   if [ $stat != 0 ]; then
-    echo "creation of item for $handle failed - cannot continue" >&2
+    echo "creation of item for $handle FAILED - cannot continue" >&2
     exit $stat
   fi
 done
 set_main_vars
+((++testcount))
 create_item_with_refs
 if [ $? != 0 ]; then
   ((++failures))
+else
+  ((++successcount))
 fi
 set_badref_vars
+((++testcount))
 STODO_REJECT_BADREFS=1 create_item_with_refs true
 stat=$?
 if [ $stat != $lie_retval ]; then
   echo "creation of item for $handle (with bad references) FAILED" >&2
   ((++failures))
 else
+  ((++successcount))
   echo "creation of $hndl [with bad/checked references] SUCCEEDED"
 fi
 for h in $ref1 $ref2 $ref3; do
+  ((++testcount))
   if ! delete_test $h; then
     ((++failures))
+  else
+    ((++successcount))
   fi
 done
+((++testcount))
 delete_test $testhndl
 if [ $? != 0 ]; then
   ((++failures))
+else
+  ((++successcount))
 fi
+((++testcount))
 delete_test $bad_testhndl
 if [ $? != 0 ]; then
   ((++failures))
+else
+  ((++successcount))
 fi
+testreport $testcount $successcount
 if [ $failures -gt 0 ]; then
   echo "$failures tests FAILED." >&2
   exit $failures
diff --git a/test/tools b/test/tools
--- a/test/tools
+++ b/test/tools
@@ -105,3 +105,14 @@ delete() {
   local handle=$1
   eval stodo delete $handle
 }
+
+testreport() {
+  local tcount=$1
+  local succcount=$2
+  if [ $tcount = $succcount ]; then
+    echo "All ($tcount) tests SUCCEEDED." >&2
+  else
+    echo -e "$tcount tests:\n   SUCCESSFUL tests: $succcount" >&2
+    echo -e "   FAILED tests: $(expr $tcount - $succcount)" >&2
+  fi
+}
