New 'clone' test and corresponding changes/fixes
clone test: clone-101; added it to runtests.

Clone implementation changes:
First, there was a change in the spec, reflected by the test: The
the new/cloned STodoTarget is now expected to have the same parent
as the original STodoTarget. That is, it will have the same
'parent_handle' and the clone will be added as one of the parent's
children. STodoTarget.initialize_copy was updated to implement this
spec. Note that the new clone needs to be added as a child to the
parent outside of 'initialize_copy' since it's not a good idea to
have the STodoTarget object doing a database query for the parent,
nor to cause an update by calling add_child. Instead 'make_clone'
(STodoTargetEditor) retrieves the parent and calls:
        parent.add_child(clone)
Note also that the 'update' call at the end of initialize_copy was
removed - The update needs to be done (or caused, or forced) outside
of the STodoTarget after changing the handle to ensure the handles
are not the same. This is done in STodoTargetEditor.make_clone.

Due to the new spec that the parent of the clone is inherited from
the original, a 'make_orphan_clone' method was added that implements
the original, "orphaned" behavior. This method has not been tested.

Also, in RedisBasedDataManager.has_key?, changed the implementation
to return a boolean rather than nil or an object:
   def has_key?(handle)
-    result = key_table[handle]
+    result = ! key_table[handle].nil?
   end

diff --git a/test/clone-101 b/test/clone-101
--- a/test/clone-101
+++ b/test/clone-101
@@ -1,6 +1,6 @@
 #!/bin/bash
 # vim: sw=2 ts=2 expandtab
-# Remove descendants test
+# Clone test
 
 # family tree diagram for test:
 #
@@ -23,6 +23,14 @@ set_main_vars() {
   ST_EMAIL=$email
   ST_ATTACH="$attchs"
   ST_DTTIME='now'
+}
+
+clone_matches() {
+  local origf=$1
+  local clonef=$2
+  orig_contents=$(grep -E -v '^children:|^handle:|^parent:' $origf)
+  clone_contents=$(grep -E -v '^children:|^handle:|^parent:' $clonef)
+  [ "$orig_contents" = "$clone_contents" ]
 }
 
 basedir=$(dirname $0)
@@ -54,6 +62,7 @@ parentD="parent-D-test-stodo$$"
 childE="child-E-test-stodo$$"
 childF="child-F-test-stodo$$"
 childG="child-G-test-stodo$$"
+cloneA="cloneA-test-stodo$$"
 testtype=task
 mainttl="remove-descendants-$$"
 newttl="This is remove-descendants test number $$."
@@ -98,82 +107,54 @@ for testhndl in $childF $childG; do
     echo "error: $intended_parent is not parent of $testhndl" >&2
   fi
 done
-#$ancestorA $parentB $parentC $parentD $childE $childF $childG
-stodo remove_d $ancestorA $parentB
-##### Check that 'remove_d $ancestorA $parentB' performed correctly.
-par=$ancestorA
-### Check $ancestorA's children:
-for tgt in $parentC $parentD $childE; do
-  if ! checkparent $tgt $par; then
-    echo "error: $par is not $tgt's parent" >&2
-  else
-    ((++successcount))
-  fi
-  ((++testcount))
-  if ! checkchild $par $tgt; then
-    echo "error: $tgt is not one of $par's children" >&2
-  else
-    ((++successcount))
-  fi
-  ((++testcount))
-done
-par=$parentC
-### Check $parentC's children:
-for tgt in $childF $childG; do
-  if ! checkparent $tgt $par; then
-    echo "error: $par is not $tgt's parent" >&2
-  else
-    ((++successcount))
-  fi
-  ((++testcount))
-  if ! checkchild $par $tgt; then
-    echo "error: $tgt is not one of $par's children" >&2
-  else
-    ((++successcount))
-  fi
-  ((++testcount))
-done
+origfile=$(mktemp /tmp/orig$$.XXXXX)
+stodo rep comp $parentC >$origfile
+stodo clone $parentC $cloneA
+orig_after_file=$(mktemp /tmp/orig-after$$.XXXXX)
+clonefile=$(mktemp /tmp/clone$$.XXXXX)
+stodo rep comp $parentC >$orig_after_file
+stodo rep comp $cloneA >$clonefile
 
-stodo remove_d $ancestorA $childG
-##### Check that 'remove_d $ancestorA $childG' performed correctly.
-par=$parentC
-### Check $parentC's children:
-for tgt in $childF; do
-  if ! checkparent $tgt $par; then
-    echo "error: $par is not $tgt's parent" >&2
-  else
-    ((++successcount))
-  fi
-  ((++testcount))
-  if ! checkchild $par $tgt; then
-    echo "error: $tgt is not one of $par's children" >&2
-  else
-    ((++successcount))
-  fi
-  ((++testcount))
-done
-### Check that $childG is no longer one of $parentC's children:
-for tgt in $childG; do
-  if checkchild $par $tgt; then
-    echo "error: $tgt is incorrectly reported as one of $par's children" >&2
-  else
-    ((++successcount))
-  fi
-  ((++testcount))
-done
+if ! check_no_children $cloneA; then
+  echo "$cloneA incorrectly has children:" >&2
+  echo -e "  \c"
+  grep children: $clonefile >&2
+else
+  ((++successcount))
+fi
+((++testcount))
 
-removedlist="$parentB $childG"
-for h in $removedlist; do
-  if [ "$(stodo report handle $h)" ]; then
-    echo "error: $h exists - it should have been removed." >&2
-  else
-    ((++successcount))
-  fi
-  ((++testcount))
-done
+if ! checkchild $ancestorA $cloneA; then
+  echo "error: $cloneA is not one of $ancestorA's children" >&2
+else
+  ((++successcount))
+fi
+((++testcount))
+
+if ! checkparent $cloneA $ancestorA; then
+  echo "error: $ancestorA is not parent of $cloneA" >&2
+else
+  ((++successcount))
+fi
+((++testcount))
+
+if ! clone_matches $origfile $clonefile; then
+  echo "Expected fields of $parentC and $cloneA do NOT match" >&2
+else
+  ((++successcount))
+fi
+((++testcount))
+
+if ! diff $origfile $orig_after_file; then
+  echo "$parentC was incorrectly changed by the clone process." >&2
+else
+  ((++successcount))
+fi
+((++testcount))
+
 [ $successcount = $testcount ]
 status=$?
-delete $ancestorA $parentB $parentC $parentD $childE $childF $childG
+delete $ancestorA $parentB $parentC $parentD $childE $childF $childG $cloneA
 stodo endtran
 testreport $testcount $successcount
 exit $status
