add test for stodo template/init

diff --git a/test/tools b/test/tools
--- a/test/tools
+++ b/test/tools
@@ -1,4 +1,5 @@
 #!/bin/bash
+# vim: ts=4 sw=4 expandtab
 
 init_tools() {
   no_h=false
@@ -63,6 +64,10 @@ create() {
   eval stodo add $ST_TYPE $STODO_OPTS
 }
 
+specpath() {
+    stodo set|awk '/^spec_path/ {print $NF}'
+}
+
 report() {
   local hndl=$1
   if ! handle_exists; then
@@ -104,6 +109,27 @@ delete() {
   fi
   local handle=$1
   eval stodo delete $handle
+}
+
+delete_test() {
+  local result=0
+  local handle=$1
+  if [ ! "$handle" ]; then
+      result=3
+  else
+      if ! [ "$STODO_KEEP_ARTIFACTS" ]; then
+          delete $handle
+          if report $handle|grep -q "$handle"; then
+              echo "deletion test FAILED in deletion of $handle"
+              result=97
+          else
+              echo "deletion test (of $handle) SUCCEEDED"
+          fi
+      else
+          echo "deletion test bypassed (keeping new item with handle: $handle"
+      fi
+  fi
+  return $result
 }
 
 testreport() {
