small improvements: reminders spec, stodo temp
Since reminders can contain more than one date and since a date can have a
comma in it (e.g., 'jan 2, 2017'), changed the delimiter for reminders to
';' (semi-colon) to allow several dates that contain commas.

stodo: make_template: Added error check for invalid type, which occurs when
the type is not specified and the argument in its place is a flag
(e.g., 'stodo temp -t <title> ...').

diff --git a/src/stodo b/src/stodo
--- a/src/stodo
+++ b/src/stodo
@@ -134,8 +134,15 @@ install_specfile() {
 
 make_template() {
   checkpath $mktmpl
+  type=$1
+  case $type in
+    -*) echo "Fatal error: invalid type: $type" >&2
+      template_help
+      return 12
+      ;;
+  esac
   if [ -w . ]; then
-    outfile=$(mktemp $1.XXXX)
+    outfile=$(mktemp $type.XXXX)
     run $mktmpl "$@" >$outfile
     if [ "$EDITOR" ]; then
       $EDITOR $outfile
@@ -151,7 +158,7 @@ report_help() {
   s='   '
   echo -e "Usage: $progname rep[ort] [options] [<report-type> [handle ...]]"
   echo -e "Options:"
-  echo -e "  -a $s         show All items, including those canceled or completed"
+  echo -e "  -a $s         show All items, including canceled or completed"
   echo -e "\nWhere <report-type> is one of:"
   echo -e "  short $s      short report - list only handles and titles"
   echo -e "  summary $s    summary report for the specified handles"
@@ -229,3 +236,5 @@ case $1 in
   *) shift; help $*
     ;;
 esac
+
+exit $?
