update to reporting interface/logic
Added a new <type-spec> "report" argument to specify priorities, statuses,
etc.  Here is a shortened version of the new "report" help (stodo -h rep):

Usage: stodo rep[ort] [<report-type> [<criteria>]]

Where <report-type> is one of:
  handle         list only matching handles
  ...
  complete       complete report for the specified handles
  ...
Where <criteria> is either:
  <type-spec>
  <space-separated list of handles> - e.g., handle1 handle2 ...
<type-spec> - one or more of the following, separated by '@':
  pri:<n1>[,<n2>[,...]]  - only priorities <n1>, <n2>, ...
  stat:<s1>[,<s2>[,...]] - only statuses <s1>, <s2>, ...
  title:<regex>          - only items whose title matches <regex>
  handle:<regex>         - only items whose handle matches <regex>

Changes to implement this new functionality (i.e., allow the user to
specify search criteria for tasks and other items based on status,
priority, item-title-regex, and handle-regex) include:
  Added a new SearchCriteria class, instances of which specify what items
  to search for, to be reported on - priority-set, status-set, etc.

  ReportManager: Changes to most of the public interface methods to
  incorporate the new logic by taking a SearchCriteria object (e.g.,
  instead of a set of handles and/or states) and using all of the
  criteria in that object to select the items to be reported on.
  Addition of the private helper method 'targets_for_criteria criteria'
  to implement the new search logic. (Note: searching based on regular-
  expressions for the title and handle are still "to-be-implemented".)
  One or two of the public methods (such as 'report_reminders') still
  need to be updated with respect to the new logic.

  ReportUtil: Changes to parse the user-specified search-criteria from
  the command-line arguments and use these criteria to build a
  SearchCriteria instance.  Changes to the method (now called 'execute')
  that calls the reporting methods of ReportManager, and some needed
  supporting implementation logic.

  TargetStateSet: Added 'count' and changed 'initialize', as needed by
  the new logic.

  stodo - the bash driver script: A couple changes needed for the new
  logic (required by main/report.rb), and updated the "help" message
  for reporting to reflect the new UI changes.

Miscellaneous small changes: updates to .gitignore; in case needed at
some point: added Gemfile, Gemfile.lock.

diff --git a/src/stodo b/src/stodo
--- a/src/stodo
+++ b/src/stodo
@@ -6,6 +6,8 @@ initproc=main/initial-processing.rb
 notifyproc=main/ongoing-processing.rb
 mktmpl=main/stodo-template.rb
 report=main/report.rb
+#!!!! - in progress, or, probably, will be abandoned:
+search=main/search.rb
 edit=main/stodo-mgmt.rb
 admin=main/stodo-admin.rb
 stodo_envpath="$STODO_PATH"
@@ -21,6 +23,9 @@ mainhelp() {
     echo -e "  combined${gap}       combine notifications with processing of \c"
     echo -e "new items"
     echo -e "  report ${gap}        display a report of existing to-do items"
+#!!!! - in progress, or, probably, will be abandoned.
+#    echo -e "  search ${gap}        handles of items matching specified \c"
+#    echo -e "criteria"
     echo -e "  del <h>...${gap}     delete targets with handles <h>, ..."
     echo -e "  stat <x> <h>...${gap}change status of handles <h>, ... to \c"
     echo -e "state-change <x>"
@@ -34,6 +39,8 @@ indepth_help() {
     rep*) report_help ;;
     temp*) template_help ;;
     sta*) state_help ;;
+#!!!! - in progress, or, probably, will be abandoned:
+    sea*) search_help ;;
   esac
 }
 
@@ -76,6 +83,11 @@ checkpath() {
 run() {
   cmd=$1; shift
   $RUBY_EXEC $STEXEC_PATH/$cmd "$@"
+  status=$?
+  if [ $status -ne 0 ]; then
+    echo "command failed [$RUBY_EXEC $STEXEC_PATH/$cmd $@]" >&2
+    exit $status
+  fi
 }
 
 process_new_items() {
@@ -95,6 +107,20 @@ do_combined_processing() {
   run $notifyproc
 }
 
+old__do_report() {
+  checkpath $report
+  modded_args=
+  case $1 in
+    -a*) shift; modded_args=$1:ignore; shift
+      ;;
+    -p*) shift; modded_args=$1:inprog; shift
+      ;;
+    -*) shift
+      ;;
+  esac
+  run $report $modded_args $*
+}
+
 do_report() {
   checkpath $report
   modded_args=
@@ -107,6 +133,21 @@ do_report() {
       ;;
   esac
   run $report $modded_args $*
+}
+
+do_search() {
+#!!!! - in progress, or, probably!!!, will be abandoned.
+  checkpath $search
+  modded_args=
+  case $1 in
+    -a*) shift; modded_args=$1:ignore; shift
+      ;;
+    -p*) shift; modded_args=$1:inprog; shift
+      ;;
+    -*) shift
+      ;;
+  esac
+  run $search $modded_args $*
 }
 
 do_edit() {
@@ -161,8 +202,8 @@ make_template() {
   fi
 }
 
-report_help() {
-  s='   '
+old___report_help() {
+  local s='   '
   echo -e "Usage: $progname rep[ort] [options] [<report-type> [handle ...]]"
   echo -e "Options:"
   echo -e "  -a $s         show All items, including canceled or completed"
@@ -182,8 +223,45 @@ report_help() {
   echo -e "completed items) -\n   For example, 'stodo rep rem:ignore'"
 }
 
+report_help() {
+  local s='   '
+  echo -e "Usage: $progname rep[ort] [<report-type> [<criteria>]]"
+  echo -e "\nWhere <report-type> is one of:"
+  echo -e "  handle $s     list only matching handles"
+  echo -e "  short $s      short report - list only handles and titles"
+  echo -e "  summary $s    summary report for the specified handles"
+  echo -e "  complete $s   complete report for the specified handles"
+  echo -e "  due $s        pending items with their \"due\" date"
+  echo -e "  remind $s     upcoming (first) reminder"
+  echo -e "  remindh $s    upcoming (first) reminder" \
+    "(with handle instead of title)"
+  echo -e "  remindall $s  all upcoming reminders"
+  echo -e "  children $s   report of all child relationships"
+  echo -e "Where <criteria> is either:"
+  echo -e "  <type-spec>"
+  echo -e "  <space-separated list of handles> - e.g., handle1 handle2 ..."
+  echo -e "<type-spec> - one or more of the following, separated by '@':"
+  echo -e "  pri:<n1>[,<n2>[,...]]  - only priorities <n1>, <n2>, ..."
+  echo -e "  stat:<s1>[,<s2>[,...]] - only statuses <s1>, <s2>, ..."
+  echo -e "  title:<regex>          - only items whose title matches <regex>"
+  echo -e "  handle:<regex>         - only items whose handle matches <regex>"
+  echo -e "\nNotes (!!!!this might need changing:):"
+  echo -e " - If <report-type> is not specified, list all target handles."
+  echo -e "   (REVISE OR REMOVE:)"
+  echo -e " - Add :ignore to ignore state (i.e., include canceled and \c"
+  echo -e "completed items) -\n   For example, 'stodo rep rem:ignore'"
+}
+
+search_help() {
+#!!!! - in progress - actually, will probably be abandoned.
+  local s='   '
+  echo -e "Usage: $progname sea[rch] <search-type> <expr>"
+  echo -e "\nWhere <search-type> is one of:"
+  echo -e "  priority $s   search for items whose priority matches <expr>"
+}
+
 template_help() {
-  s='     '
+  local s='     '
   echo -e "Usage: $progname temp [<type>] [options]"
   echo -e "Where <type> is one of:\c"
   echo -e " task, memo, appointment (or event), project"
@@ -226,6 +304,9 @@ case $1 in
   comb*) do_combined_processing
     ;;
   rep*) shift; do_report $*
+    ;;
+  sea*) shift; do_search $*
+#!!!!          ^^^^^^^^^ in progress, or, probably, will be abandoned.
     ;;
   del*)
     shift;
