improvements to "stodo temp" and reporting
Implemented a method of, for the 'stodo temp' (spec-file templating)
option, installing the new spec file to the 'spec_path' directory without
committing it to be processed by inserting the string 'type: template'
into the spec file.  The user edits this file (when the editor [$EDITOR env.
var] is invoked via 'stodo temp') and, to allow the file to be processed,
removes that line before writing the file and exiting the editor.  If the
'type: template' line remains in the file (below the earlier, valid
'type: ...' line) the 'stodo init' command will ignore the spec file, leaving
it in place.  The user can then later remove the 'type: template' line to
allow the file to be processed - i.e., used to create a new STodoTarget.

Changed the reporting (report.rb) logic such that if no states are specified
by the user, only active "STodoTarget"s are reported.  For example,
'stodo report due' lists only items that are in-progress or suspended, not
canceled or completed - to list all items, one can run: 'stodo report due:e'
(which matches all states, since the letter e occurs in all four state
names).  The assumption here is that the user will not usually need to know
about "STodoTarget"s that are canceled or completed.

.stodo_utilities: Added a couple more convenience aliases.

diff --git a/src/stodo b/src/stodo
--- a/src/stodo
+++ b/src/stodo
@@ -9,6 +9,7 @@ report=main/report.rb
 edit=main/stodo-mgmt.rb
 admin=main/stodo-admin.rb
 stodo_envpath="$STODO_PATH"
+specpath_expr='^# *spec-path:'
 
 
 mainhelp() {
@@ -118,6 +119,19 @@ do_backup() {
   run $admin backup $*
 }
 
+install_specfile() {
+  file=$1
+  specpath=$(awk "/$specpath_expr/"'{print $NF}' $file)
+  if [ "$specpath" ]; then
+    echo "Installing $file to $specpath" >&2
+    mv $file $specpath || {
+      status=$?
+      echo "Error: Move of $file to $specpath failed." >&2
+    }
+  fi
+  return $status
+}
+
 make_template() {
   checkpath $mktmpl
   if [ -w . ]; then
@@ -126,6 +140,8 @@ make_template() {
     if [ "$EDITOR" ]; then
       $EDITOR $outfile
     fi
+    install_specfile $outfile
+    exit $?
   else
     run $mktmpl "$@"
   fi
